/**
 * subject-domains.ts — curated subject -> domain map for the culture drill
 * stamp. GENERATED Jul 31 2026 from the top-1500 corpus subjects
 * (scripts/_qa/subjects-top.txt), LLM-classified + spot-audited. Domains:
 * music | hollywood | political | historic | military | royalty | literary |
 * space-science | sports | other. Regenerate from a fresh subject dump when
 * the corpus head shifts.
 */
export const SUBJECT_DOMAINS: Record<string, string> = {
  'beatles': 'music',
  'marilyn monroe': 'hollywood',
  'ronald reagan': 'political',
  'harry s truman': 'political',
  'john f kennedy': 'political',
  'richard nixon': 'political',
  'franklin d roosevelt': 'political',
  'wizard of oz': 'hollywood',
  'rolling stones': 'music',
  'abraham lincoln': 'political',
  'dwight d eisenhower': 'political',
  'theodore roosevelt': 'political',
  'walt disney': 'hollywood',
  'gerald ford': 'political',
  'ted williams': 'sports',
  'declaration of independence': 'political',
  'audrey hepburn': 'hollywood',
  'elvis presley': 'music',
  'charles schulz': 'literary',
  'william h taft': 'political',
  'enola gay': 'military',
  'bill clinton': 'political',
  'star wars': 'hollywood',
  'george bush': 'political',
  'calvin coolidge': 'political',
  'james bond': 'hollywood',
  'joe dimaggio': 'sports',
  'u s grant': 'political',
  'woodrow wilson': 'political',
  'supreme court': 'political',
  'gone with the wind': 'hollywood',
  'bob dylan': 'music',
  'led zeppelin': 'music',
  'lyndon b johnson': 'political',
  'the who': 'music',
  'star trek': 'hollywood',
  'gene cernan': 'space-science',
  'michael jackson': 'music',
  'pink floyd': 'music',
  'herbert hoover': 'political',
  'grace kelly': 'hollywood',
  'grover cleveland': 'political',
  'james stewart': 'hollywood',
  'charles lindbergh': 'military',
  'clark gable': 'hollywood',
  'orville wright': 'military',
  'three stooges': 'hollywood',
  'katharine hepburn': 'hollywood',
  'jimmy carter': 'political',
  'ny yankees': 'sports',
  'edmund hillary': 'historic',
  'fred astaire': 'hollywood',
  'charlie duke': 'space-science',
  'benjamin harrison': 'political',
  'james monroe': 'political',
  'clint eastwood': 'hollywood',
  'william mckinley': 'political',
  'the beatles': 'music',
  'george w bush': 'political',
  'john lennon': 'music',
  'george washington': 'political',
  'frank sinatra': 'music',
  'john quincy adams': 'political',
  'fred haise': 'space-science',
  'alan bean': 'space-science',
  'titanic': 'other',
  'andy warhol': 'literary',
  'andrew jackson': 'political',
  'mickey mouse': 'hollywood',
  'norman rockwell': 'literary',
  'warren g harding': 'political',
  'jacqueline kennedy': 'political',
  'lucille ball': 'hollywood',
  'mother teresa': 'historic',
  'james madison': 'political',
  'thomas jefferson': 'political',
  'rutherford b hayes': 'political',
  'eric clapton': 'music',
  'joan crawford': 'hollywood',
  'franklin d roosevelt typed': 'political',
  'john wayne': 'hollywood',
  'judy garland': 'hollywood',
  'elizabeth taylor': 'hollywood',
  'ingrid bergman': 'hollywood',
  'donald trump': 'political',
  'jimi hendrix': 'music',
  'iwo jima': 'military',
  'louis armstrong': 'music',
  'kennedy assassination': 'political',
  'horse racing': 'sports',
  'vivien leigh': 'hollywood',
  'douglas macarthur': 'military',
  'barack obama': 'political',
  'marlene dietrich': 'hollywood',
  'bruce springsteen': 'music',
  'edgar mitchell': 'space-science',
  'bette davis': 'hollywood',
  'winston churchill': 'political',
  'taylor swift': 'music',
  'princess diana': 'royalty',
  'james lovell': 'space-science',
  'james a garfield': 'political',
  'brigitte bardot': 'hollywood',
  'samuel l clemens': 'literary',
  'jayne mansfield': 'hollywood',
  'paul newman': 'hollywood',
  'cary grant': 'hollywood',
  'john young': 'space-science',
  'charlie chaplin': 'hollywood',
  'margaret thatcher': 'political',
  'elton john': 'music',
  'james buchanan': 'political',
  'errol flynn': 'hollywood',
  'dave scott': 'space-science',
  'alfred hitchcock': 'hollywood',
  'benito mussolini': 'political',
  'robert f kennedy': 'political',
  'stan laurel': 'hollywood',
  'millard fillmore': 'political',
  'jim irwin': 'space-science',
  'harry houdini': 'hollywood',
  'dean martin': 'music',
  'william t sherman': 'military',
  'martin van buren': 'political',
  'charles dickens': 'literary',
  'shirley temple': 'hollywood',
  'dwight d eisenhower typed': 'political',
  'queen elizabeth ii': 'royalty',
  'humphrey bogart': 'hollywood',
  'al pacino': 'hollywood',
  'harry s truman typed': 'political',
  'david bowie': 'music',
  'andrew johnson': 'political',
  'dr seuss': 'literary',
  'mercury astronauts': 'space-science',
  'ty cobb': 'sports',
  'boris karloff': 'hollywood',
  'amelia earhart': 'military',
  'gary cooper': 'hollywood',
  'dalai lama': 'historic',
  'stephen king': 'literary',
  'sophia loren': 'hollywood',
  'chester a arthur': 'political',
  'franklin pierce': 'political',
  'paul mccartney': 'music',
  'johnny cash': 'music',
  'tiger woods': 'sports',
  'john tyler': 'political',
  'napoleon': 'political',
  'natalie wood': 'hollywood',
  'gordon cooper': 'space-science',
  'beach boys': 'music',
  'salvador dali': 'literary',
  'dna': 'space-science',
  'batman': 'hollywood',
  'pablo picasso': 'literary',
  'john adams': 'political',
  'marlon brando': 'hollywood',
  'marc chagall': 'literary',
  'george bernard shaw': 'literary',
  'william f buffalo bill': 'historic',
  'john hancock': 'political',
  'ben hogan': 'sports',
  'grateful dead': 'music',
  'disney': 'hollywood',
  'george s patton': 'military',
  'ava gardner': 'hollywood',
  'ernest hemingway': 'literary',
  'nelson mandela': 'political',
  'martin luther king': 'political',
  'mae west': 'hollywood',
  'richard nixon book': 'political',
  'orson welles': 'hollywood',
  'steve mcqueen': 'hollywood',
  'mikhail gorbachev': 'political',
  'fidel castro': 'political',
  'jack nicholson': 'hollywood',
  'jack london': 'literary',
  'chuck yeager': 'military',
  'roger maris': 'sports',
  'jefferson davis': 'political',
  'queen victoria': 'royalty',
  'harrison schmitt': 'space-science',
  'jack dempsey': 'sports',
  'bruce lee': 'hollywood',
  'basil rathbone': 'hollywood',
  'queen': 'music',
  'laurel and hardy': 'hollywood',
  'james k polk': 'political',
  'valentina tereshkova': 'space-science',
  'guns n roses': 'music',
  'bill hanna': 'hollywood',
  'w c fields': 'hollywood',
  'easy rider': 'hollywood',
  'james cagney': 'hollywood',
  'robert e lee': 'military',
  'charles conrad': 'space-science',
  'enrico caruso': 'music',
  'sandy koufax': 'sports',
  'j edgar hoover': 'political',
  'madonna': 'music',
  'matt groening': 'hollywood',
  'alexei leonov': 'space-science',
  'eleanor roosevelt': 'political',
  'jack nicklaus': 'sports',
  'boston red sox': 'sports',
  'jack ruby': 'historic',
  'frank borman': 'space-science',
  'civil war': 'other',
  'james dean': 'hollywood',
  'david ben gurion': 'political',
  'william henry harrison': 'political',
  'u s grant signature': 'political',
  'prince': 'music',
  'irving berlin': 'music',
  'hedy lamarr': 'hollywood',
  'lauren bacall': 'hollywood',
  'johnny depp': 'hollywood',
  'fay wray': 'hollywood',
  'helen keller': 'historic',
  'zachary taylor': 'political',
  'joe louis': 'sports',
  'rita hayworth': 'hollywood',
  'barbra streisand': 'music',
  'mary blair': 'hollywood',
  'arnold palmer': 'sports',
  'jefferson airplane': 'music',
  'jimi hendrix experience': 'music',
  'barbara stanwyck': 'hollywood',
  'bill clinton book': 'political',
  'greta garbo': 'hollywood',
  'p t barnum': 'historic',
  'william h taft typed': 'political',
  'jim henson': 'hollywood',
  'henry wadsworth longfellow': 'literary',
  'van halen': 'music',
  'groucho marx': 'hollywood',
  'duke ellington': 'music',
  'sammy davis': 'music',
  'piggybanx good': 'other',
  'four presidents': 'political',
  'theodore roosevelt typed letter': 'political',
  'george gershwin': 'music',
  'ronald reagan signature': 'political',
  'gene kranz': 'space-science',
  'myron waldman animation cel': 'hollywood',
  'harrison ford': 'hollywood',
  'glenn miller': 'music',
  'hillary clinton': 'political',
  'arthur conan doyle': 'literary',
  'ronald reagan book': 'political',
  'ansel adams': 'literary',
  'john f kennedy typed': 'political',
  'world war ii': 'other',
  'our gang': 'hollywood',
  'patsy cline': 'music',
  'betty grable': 'hollywood',
  'frank lloyd wright': 'literary',
  'bugs bunny': 'hollywood',
  'robert redford': 'hollywood',
  'b b king': 'music',
  'oliver wendell holmes': 'literary',
  'kiss': 'music',
  'frankenstein': 'hollywood',
  'rocky marciano': 'sports',
  'leonard bernstein': 'music',
  'ringo starr': 'music',
  'tom petty': 'music',
  'harper lee': 'literary',
  'carl barks': 'hollywood',
  'robert frost': 'literary',
  'john philip sousa': 'music',
  'richard nixon typed letter': 'political',
  'victor hugo': 'literary',
  'gregory peck': 'hollywood',
  'woodrow wilson typed letter': 'political',
  'jonas salk': 'space-science',
  'lyndon b johnson typed': 'political',
  'hank aaron': 'sports',
  'george harrison': 'music',
  'disney lorcana en': 'hollywood',
  'henry clay': 'political',
  'mary pickford': 'hollywood',
  'willie mays': 'sports',
  'vince lombardi': 'sports',
  'aerosmith': 'music',
  'rosa parks': 'political',
  'john d rockefeller': 'historic',
  'edward h white ii': 'space-science',
  'moonwalkers': 'space-science',
  'bela lugosi': 'hollywood',
  'the doors': 'music',
  'laurence olivier': 'hollywood',
  'josephine baker': 'music',
  'bing crosby': 'music',
  'academy award winners': 'hollywood',
  'rudolph valentino': 'hollywood',
  'christopher reeve': 'hollywood',
  'barack obama book': 'political',
  'chuck berry': 'music',
  'stevie ray vaughan': 'music',
  'robert deniro': 'hollywood',
  'louis pasteur': 'space-science',
  'daniel webster': 'political',
  'albert schweitzer': 'space-science',
  'douglas fairbanks': 'hollywood',
  'robert o neill': 'military',
  'mel blanc': 'hollywood',
  'bee gees': 'music',
  'erwin rommel': 'military',
  'aaron burr': 'political',
  'jane russell': 'hollywood',
  'astronauts': 'space-science',
  'herbert hoover typed letter': 'political',
  'joe biden': 'political',
  'roger bannister': 'sports',
  'three tenors': 'music',
  'buddy holly': 'music',
  'casablanca': 'hollywood',
  'vincent price': 'hollywood',
  'beatles starr ringo': 'music',
  'apple computer': 'space-science',
  'frederick douglass': 'political',
  'actors and actresses': 'hollywood',
  'mercury 7': 'space-science',
  'actresses': 'hollywood',
  'the sopranos': 'hollywood',
  'jack kerouac': 'literary',
  'les paul': 'music',
  'giacomo puccini': 'music',
  'al capone': 'historic',
  'james fenimore cooper': 'literary',
  'the rolling stones': 'music',
  'james brown': 'music',
  'lon chaney': 'hollywood',
  'gloria swanson': 'hollywood',
  'spencer tracy': 'hollywood',
  'king george iii': 'royalty',
  'wilt chamberlain': 'sports',
  'saddam hussein': 'political',
  'pope john paul ii': 'historic',
  'julie andrews': 'hollywood',
  'calvin coolidge typed letter': 'political',
  'super break pieces': 'other',
  'howard hughes': 'historic',
  'john steinbeck': 'literary',
  'joey ramone': 'music',
  'lana turner': 'hollywood',
  'cole porter': 'music',
  'bob hope': 'hollywood',
  'nat king cole': 'music',
  'james bond connery sean': 'hollywood',
  'carole lombard': 'hollywood',
  'gene tierney': 'hollywood',
  'chester nimitz': 'military',
  'ny mets': 'sports',
  'sylvester stallone': 'hollywood',
  'harry potter': 'hollywood',
  'buffalo bill': 'historic',
  'miracle on ice': 'sports',
  'kirk douglas': 'hollywood',
  'j k rowling': 'literary',
  'mohandas gandhi': 'political',
  'herbert hoover book': 'political',
  'gerald ford book': 'political',
  'sex pistols': 'music',
  'maria callas': 'music',
  'charlton heston': 'hollywood',
  'john j pershing': 'military',
  'claude monet': 'literary',
  'walter payton': 'sports',
  'janis joplin': 'music',
  'ginger rogers': 'hollywood',
  'peter sellers': 'hollywood',
  'arnold schwarzenegger': 'hollywood',
  'chuck jones': 'hollywood',
  'billy joel': 'music',
  'pete rose': 'sports',
  'larry bird': 'sports',
  'bobby jones': 'sports',
  'the eagles': 'music',
  'the clash': 'music',
  'norma shearer': 'hollywood',
  'superman': 'hollywood',
  'leroy neiman': 'literary',
  'omar bradley': 'military',
  'p g t beauregard': 'military',
  'challenger': 'space-science',
  'jean harlow': 'hollywood',
  'rudyard kipling': 'literary',
  'samuel f b morse': 'space-science',
  'johnny weissmuller': 'hollywood',
  'bob marley': 'music',
  'sammy davis jr': 'music',
  'zz top': 'music',
  'margaret mitchell': 'literary',
  'horatio nelson': 'military',
  'john wayne signature': 'hollywood',
  'woodstock': 'music',
  'james taylor': 'music',
  'liberty bell': 'other',
  'ken mattingly': 'space-science',
  'miles davis': 'music',
  'edward g robinson': 'hollywood',
  'robert mitchum': 'hollywood',
  'willie nelson': 'music',
  'steven spielberg': 'hollywood',
  'frank sinatra signature': 'music',
  'sgt alvin c york': 'military',
  'rod serling': 'hollywood',
  'bettie page': 'hollywood',
  'amelia earhart signature': 'military',
  'johnny unitas': 'sports',
  'sarah bernhardt': 'hollywood',
  'william powell': 'hollywood',
  'sugar ray robinson': 'sports',
  'samuel l clemens signature': 'literary',
  'eddie rickenbacker': 'military',
  'wilbur wright': 'military',
  'george a custer': 'military',
  'sally ride': 'space-science',
  'auguste rodin': 'literary',
  'thomas jefferson and james madison': 'political',
  'charles schulz sketch': 'literary',
  'stephen king book': 'literary',
  'cream': 'music',
  'roy rogers': 'hollywood',
  'doris day': 'hollywood',
  'donald duck': 'hollywood',
  'chiang kai shek': 'political',
  'tennessee williams': 'literary',
  'harriet beecher stowe': 'literary',
  'benjamin franklin': 'political',
  'bobby orr': 'sports',
  'satchel paige': 'sports',
  'oliver ellsworth': 'political',
  'lou costello': 'hollywood',
  'alec guinness': 'hollywood',
  'peter o toole': 'hollywood',
  'bon jovi': 'music',
  'little richard': 'music',
  'wright brothers': 'military',
  'sigmund freud': 'space-science',
  'charlie chaplin signature': 'hollywood',
  'eyvind earle': 'hollywood',
  'franklin d roosevelt signature': 'political',
  'samuel francis smith': 'literary',
  'beatles signatures': 'music',
  'claudette colbert': 'hollywood',
  'walt disney signature': 'hollywood',
  'lynyrd skynyrd': 'music',
  'never quit': 'other',
  'alexander hamilton': 'political',
  'boston': 'music',
  'alexandre dumas': 'literary',
  'h g wells': 'literary',
  'igor stravinsky': 'music',
  'marx brothers': 'hollywood',
  'clara barton': 'historic',
  'emile zola': 'literary',
  'hank greenberg': 'sports',
  'chester w nimitz': 'military',
  'aretha franklin': 'music',
  'neil young': 'music',
  'first ladies': 'political',
  'donna reed': 'hollywood',
  'lee harvey oswald': 'historic',
  'theodore roosevelt signature': 'political',
  'rutherford b hayes signature': 'political',
  'jerry lee lewis': 'music',
  'film stars': 'hollywood',
  'marvin gaye': 'music',
  'jerry garcia': 'music',
  'robert stroud': 'historic',
  'monty python': 'hollywood',
  'mother teresa typed letter': 'historic',
  'claude rains': 'hollywood',
  'nolan ryan': 'sports',
  'connie mack': 'sports',
  'charles schulz book': 'literary',
  'henry fonda': 'hollywood',
  'tyrone power': 'hollywood',
  'princess grace': 'royalty',
  'susan hayward': 'hollywood',
  'peter lorre': 'hollywood',
  'zane grey': 'literary',
  'joe frazier': 'sports',
  'baseballs': 'sports',
  'al hirschfeld': 'literary',
  'george michael': 'music',
  'maurice sendak': 'literary',
  'walter lantz': 'hollywood',
  'alexander graham bell': 'space-science',
  'james monroe document': 'political',
  'william h taft signature': 'political',
  'flying tigers': 'military',
  'john wooden': 'sports',
  'george w bush book': 'political',
  'beatles mccartney paul': 'music',
  'edith head': 'hollywood',
  'snow white': 'hollywood',
  'black sabbath': 'music',
  'w c handy': 'music',
  'clayton moore': 'hollywood',
  'alice cooper': 'music',
  'yogi berra': 'sports',
  'j paul getty': 'historic',
  'tom stafford': 'space-science',
  'jack swigert': 'space-science',
  'will rogers': 'hollywood',
  'philip h sheridan': 'military',
  'king george vi': 'royalty',
  'deke slayton': 'space-science',
  'ronald and nancy reagan': 'political',
  'diana': 'royalty',
  'allen ginsberg': 'literary',
  'clara bow': 'hollywood',
  'u s grant document': 'political',
  'joan miro': 'literary',
  'pearl jam': 'music',
  'bill russell': 'sports',
  'andrew johnson signature': 'political',
  'joe montana': 'sports',
  'harry s truman book': 'political',
  'the ramones': 'music',
  'ella fitzgerald': 'music',
  'peter max': 'literary',
  'happy days': 'hollywood',
  'elon musk': 'historic',
  'derek jeter': 'sports',
  'pappy boyington': 'military',
  'patrick henry': 'political',
  'roger federer': 'sports',
  'millard fillmore signature': 'political',
  'ian fleming': 'literary',
  'friz freleng': 'hollywood',
  'boston celtics': 'sports',
  'beatles sutcliffe stuart': 'music',
  'bill haley': 'music',
  'frank zappa': 'music',
  'tom hanks': 'hollywood',
  'william holden': 'hollywood',
  'stan lee': 'literary',
  'john williams': 'music',
  'apple': 'other',
  'roy orbison': 'music',
  'ray bradbury': 'literary',
  'jerome kern': 'music',
  'doolittle s raiders': 'military',
  'brooklyn dodgers': 'sports',
  'lyndon b johnson book': 'political',
  'harold lloyd': 'hollywood',
  'raquel welch': 'hollywood',
  'richard strauss': 'music',
  'rick nelson': 'music',
  'bruce springsteen album': 'music',
  'martin luther king jr': 'political',
  'henry m stanley': 'historic',
  'arturo toscanini': 'music',
  'andy griffith show': 'hollywood',
  'guenter wendt': 'space-science',
  'booker t washington': 'political',
  'julia ward howe': 'literary',
  'deep purple': 'music',
  'tom cruise': 'hollywood',
  'elvis presley signature': 'music',
  'gene kelly': 'hollywood',
  'richard burton': 'hollywood',
  'vint cerf': 'space-science',
  'billie burke': 'hollywood',
  'leslie howard': 'hollywood',
  'elsa lanchester': 'hollywood',
  'lance armstrong': 'sports',
  'eugene o neill': 'literary',
  'george c marshall': 'military',
  'moody blues': 'music',
  'audie murphy': 'military',
  'alfred lord tennyson': 'literary',
  'bob kane': 'literary',
  'maxfield parrish': 'literary',
  'the sex pistols': 'music',
  'robert f kennedy typed': 'political',
  'kurt vonnegut': 'literary',
  'whitney houston': 'music',
  'susan b anthony': 'political',
  'carl sandburg': 'literary',
  'franz liszt': 'music',
  'marquis de lafayette': 'military',
  'autograph album': 'other',
  'eric clapton album': 'music',
  'robert frost book': 'literary',
  'aerosmith album': 'music',
  'abbott and costello': 'hollywood',
  'montgomery clift': 'hollywood',
  'phil collins': 'music',
  'rolling stones signatures': 'music',
  'robert taylor': 'hollywood',
  'tony curtis': 'hollywood',
  'guglielmo marconi': 'space-science',
  'keith haring': 'literary',
  'honeymooners': 'hollywood',
  'george b mcclellan': 'military',
  'edgar rice burroughs': 'literary',
  'steve reeves': 'hollywood',
  'wernher von braun': 'space-science',
  'matt groening sketch': 'hollywood',
  'beach boys album': 'music',
  'autograph album autograph album': 'other',
  'world war ii print': 'military',
  'billie holiday': 'music',
  'yul brynner': 'hollywood',
  'james h doolittle': 'military',
  'myrna loy': 'hollywood',
  'henry wells': 'historic',
  'jackie gleason': 'hollywood',
  'tippi hedren': 'hollywood',
  'king edward viii': 'royalty',
  'nobel prize winners': 'space-science',
  'winston churchill signature': 'political',
  'victoria': 'royalty',
  'sean connery': 'hollywood',
  'mick jagger': 'music',
  'actors': 'hollywood',
  'rudolf nureyev': 'literary',
  'carl perkins': 'music',
  'william mckinley document': 'political',
  'arthur miller': 'literary',
  'andrew carnegie': 'historic',
  'richard e byrd': 'historic',
  'al worden': 'space-science',
  'bobby darin': 'music',
  'red grange': 'sports',
  'truman capote': 'literary',
  'eddie van halen': 'music',
  'hank williams': 'music',
  'blues legends': 'music',
  'myron waldman': 'hollywood',
  'winston churchill typed letter': 'political',
  'joshua lawrence chamberlain': 'military',
  'ny giants': 'sports',
  'bill anders': 'space-science',
  'honus wagner': 'sports',
  'john jay': 'political',
  'jean cocteau': 'literary',
  'ronald reagan typed letter': 'political',
  'roger waters': 'music',
  'charles sumner': 'political',
  'andrew jackson document': 'political',
  'revolutionary war': 'military',
  'gerald ford typed letter': 'political',
  'walt whitman': 'literary',
  'buster crabbe': 'hollywood',
  'james a garfield signature': 'political',
  'jim mcdivitt': 'space-science',
  'five presidents': 'political',
  'stephen sondheim': 'music',
  'sergei rachmaninoff': 'music',
  'robert todd lincoln': 'political',
  'muddy waters': 'music',
  'f scott fitzgerald': 'literary',
  'ronald reagan program': 'political',
  'gerald ford group lot': 'political',
  'rudy giuliani': 'political',
  'b la lugosi': 'hollywood',
  'bo diddley': 'music',
  'the godfather': 'hollywood',
  'keith richards': 'music',
  'andrew johnson document': 'political',
  'rutherford b hayes document': 'political',
  'henry ford': 'historic',
  'luciano pavarotti': 'music',
  'christopher lee': 'hollywood',
  'joe namath': 'sports',
  'gutzon borglum': 'literary',
  'stan musial': 'sports',
  'cosmonauts': 'space-science',
  'ralph waldo emerson': 'literary',
  'roger clemens': 'sports',
  'jim morrison': 'music',
  'tallulah bankhead': 'hollywood',
  'anna may wong': 'hollywood',
  'ayn rand': 'literary',
  'jules verne': 'literary',
  'audrey hepburn signature': 'hollywood',
  'andrew wyeth': 'literary',
  'dustin hoffman': 'hollywood',
  'peter cushing': 'hollywood',
  'winfield scott': 'military',
  'jane goodall': 'space-science',
  'grover cleveland signature': 'political',
  'jefferson davis signature': 'political',
  'william t sherman signature': 'military',
  'andy warhol signature': 'literary',
  'irving thalberg': 'hollywood',
  'charles dickens signature': 'literary',
  'agatha christie': 'literary',
  'cab calloway': 'music',
  'the kinks': 'music',
  'leo tolstoy': 'literary',
  'texas': 'other',
  'prince s personally owned': 'music',
  'mission control': 'space-science',
  'jimmy carter books': 'political',
  'leroy neiman print': 'literary',
  'authors': 'literary',
  'george iii': 'royalty',
  'three stooges howard moe': 'hollywood',
  'britney spears': 'music',
  'anna pavlova': 'literary',
  'edith piaf': 'music',
  'midnight cowboy': 'hollywood',
  'loretta young': 'hollywood',
  'gene wilder': 'hollywood',
  'rod stewart': 'music',
  'golda meir': 'political',
  'henri matisse': 'literary',
  'casey stengel': 'sports',
  'cincinnati reds': 'sports',
  'william mckinley typed letter': 'political',
  'king george v': 'royalty',
  'linda darnell': 'hollywood',
  'james j corbett': 'sports',
  'rock hudson': 'hollywood',
  'frank follmer': 'hollywood',
  'frank capra': 'hollywood',
  'william f': 'historic',
  'queen victoria signature': 'royalty',
  'cary grant signature': 'hollywood',
  'george bush typed letter': 'political',
  'roy lichtenstein': 'literary',
  'j r r tolkien': 'literary',
  'john garfield': 'hollywood',
  'jodie foster': 'hollywood',
  'federico fellini': 'hollywood',
  'sam houston': 'political',
  'dwight d eisenhower book': 'political',
  'george bush book': 'political',
  'duke of wellington': 'military',
  'buster keaton': 'hollywood',
  'prohibition': 'historic',
  'burt lancaster': 'hollywood',
  'johannes brahms': 'music',
  'carlo gambino': 'historic',
  'ozzy osbourne': 'music',
  'malcolm x': 'political',
  'meyer lansky': 'historic',
  'heart': 'music',
  'leonid brezhnev': 'political',
  'giuseppe verdi': 'music',
  'william s hart': 'hollywood',
  'chester a arthur signature': 'political',
  'peter lawford': 'hollywood',
  'william mckinley signature': 'political',
  'w somerset maugham': 'literary',
  'supreme court group lot': 'political',
  'ac dc': 'music',
  'marion davies': 'hollywood',
  'jim thorpe': 'sports',
  'george burns': 'hollywood',
  'virgil ross': 'hollywood',
  'super dragon ball heroes': 'hollywood',
  'kakawow phantom': 'other',
  'artbox harry potter': 'hollywood',
  'harry s truman signature': 'political',
  'robert crumb': 'literary',
  'supreme court justices': 'political',
  'frederic auguste bartholdi': 'literary',
  'paul revere': 'political',
  'jane fonda': 'hollywood',
  'james j braddock': 'sports',
  'bram stoker': 'literary',
  'kareem abdul jabbar': 'sports',
  'calvin coolidge white house': 'political',
  'willy wonka': 'hollywood',
  'mike mitchell': 'literary',
  'tony bennett': 'music',
  'walt cunningham': 'space-science',
  'yitzhak rabin': 'political',
  'ty cobb signature': 'sports',
  'thornton wilder': 'literary',
  'george c scott': 'hollywood',
  'janet leigh': 'hollywood',
  'boris karloff signature': 'hollywood',
  'alexander fleming': 'space-science',
  'michael jackson album': 'music',
  'eva peron': 'political',
  'james stewart group lot': 'hollywood',
  'eddie cantor': 'hollywood',
  'u2': 'music',
  'the police': 'music',
  'motley crue': 'music',
  'carmen miranda': 'hollywood',
  'edmund gwenn': 'hollywood',
  'bert lahr': 'hollywood',
  'def leppard': 'music',
  'johnny carson': 'hollywood',
  'antonio lopez': 'literary',
  'j pierpont morgan': 'historic',
  'max baer': 'sports',
  'helen keller signature': 'historic',
  'theda bara': 'hollywood',
  'jules massenet': 'music',
  'bruce mccandless': 'space-science',
  'clarence darrow': 'historic',
  'tom mix': 'hollywood',
  'harley davidson': 'other',
  'watergate': 'political',
  'roy orbison signature': 'music',
  'anna nicole smith': 'hollywood',
  'georgy zhukov': 'military',
  'henry miller': 'literary',
  'dale earnhardt': 'sports',
  'magic johnson': 'sports',
  'john coltrane': 'music',
  'richard wagner': 'music',
  'bear': 'other',
  'maureen o hara': 'hollywood',
  'bill gates': 'historic',
  'gloria grahame': 'hollywood',
  'marilyn monroe oversized': 'hollywood',
  'michael j fox': 'hollywood',
  'evel knievel': 'sports',
  'john denver': 'music',
  'aldous huxley': 'literary',
  'james d watson': 'space-science',
  'eleanor roosevelt typed letter': 'political',
  'barry bonds': 'sports',
  'washington irving': 'literary',
  'roger maris signature': 'sports',
  'roy campanella': 'sports',
  'richard gordon': 'space-science',
  'joan fontaine': 'hollywood',
  'rabindranath tagore': 'literary',
  'john s mosby': 'military',
  'joseph lister': 'space-science',
  'norman rockwell book': 'literary',
  'margaret thatcher book': 'political',
  'montgomery of alamein': 'military',
  'john paul ii': 'historic',
  'phil spector': 'music',
  'john lee hooker': 'music',
  'president john f kennedy': 'political',
  'jimmy hoffa': 'historic',
  'david niven': 'hollywood',
  'wwii battle': 'military',
  'grease': 'hollywood',
  'sharon tate': 'hollywood',
  'robert wadlow': 'historic',
  'van morrison': 'music',
  'napoleon letter': 'military',
  'allman brothers': 'music',
  'hindenburg': 'historic',
  'roberto clemente': 'sports',
  'jake lamotta': 'sports',
  'franklin pierce signature': 'political',
  'indira gandhi': 'political',
  'sinclair lewis': 'literary',
  'john barrymore': 'hollywood',
  'billy wilder': 'hollywood',
  'mickey cochrane': 'sports',
  'george washington carver': 'space-science',
  'jimmie foxx': 'sports',
  'andy warhol book': 'literary',
  'theodore roosevelt white house': 'political',
  'musicians': 'music',
  'jim brown': 'sports',
  'elizabeth ii': 'royalty',
  'george hurrell': 'literary',
  'red skelton': 'hollywood',
  'william shatner': 'hollywood',
  'king edward vii': 'royalty',
  'edward teller': 'space-science',
  'lee marvin': 'hollywood',
  'john steinbeck signature': 'literary',
  'cartoonists': 'literary',
  'ted kennedy': 'political',
  'jack lemmon': 'hollywood',
  'joe louis signature': 'sports',
  'georgia o keeffe': 'literary',
  'winfield scott hancock': 'military',
  'leon trotsky': 'political',
  'ramones': 'music',
  'william jennings bryan': 'political',
  'james stewart sketch': 'hollywood',
  'hillary clinton book': 'political',
  'charles laughton': 'hollywood',
  'dizzy gillespie': 'music',
  'al jolson': 'music',
  'rex harrison': 'hollywood',
  'grover cleveland document': 'political',
  'warren g harding document': 'political',
  'woodstock music': 'music',
  'fats domino': 'music',
  'roger moore': 'hollywood',
  'duran duran': 'music',
  'william h seward': 'political',
  'ny knicks': 'sports',
  'elizabeth taylor signature': 'hollywood',
  'kim novak': 'hollywood',
  'oscar wilde': 'literary',
  'pierre auguste renoir': 'literary',
  'william cullen bryant': 'literary',
  'four horsemen': 'sports',
  'gina lollobrigida': 'hollywood',
  'grover cleveland white house': 'political',
  'christa mcauliffe': 'space-science',
  'donald trump book': 'political',
  'indiana jones': 'hollywood',
  'bud abbott': 'hollywood',
  'king george iii signature': 'royalty',
  'yoko ono': 'music',
  'brigham young': 'historic',
  'dwight d eisenhower signature': 'political',
  'john quincy adams signature': 'political',
  'j edgar hoover typed': 'political',
  'king hussein': 'royalty',
  'richard rodgers': 'music',
  'james longstreet': 'military',
  'gene tunney': 'sports',
  'edwin booth': 'hollywood',
  'david g farragut': 'military',
  'charles l dodgson': 'literary',
  'john ericsson': 'space-science',
  'john singer sargent': 'literary',
  'van halen album': 'music',
  'rogers hornsby': 'sports',
  'cleveland browns': 'sports',
  'cecil beaton': 'literary',
  'oasis': 'music',
  'nirvana': 'music',
  'chicago': 'music',
  'sal mineo': 'hollywood',
  'bonanza': 'hollywood',
  'mike tyson': 'sports',
  'barbara eden': 'hollywood',
  'melvin purvis': 'historic',
  'oliver wolcott': 'political',
  'eric clapton signature': 'music',
  'queen victoria document': 'royalty',
  'rusty schweickart': 'space-science',
  'linus pauling': 'space-science',
  'humphrey bogart signature': 'hollywood',
  'pablo casals': 'music',
  'gene krupa': 'music',
  'orson welles signature': 'hollywood',
  'alan ladd': 'hollywood',
  'benjamin harrison signature': 'political',
  'joseph bonanno': 'historic',
  'veronica lake': 'hollywood',
  'clyde w tombaugh': 'space-science',
  'floyd patterson': 'sports',
  'jayne mansfield signature': 'hollywood',
  'village people': 'music',
  'edwin m stanton': 'political',
  'cy young': 'sports',
  'deep purple album': 'music',
  'elton john album': 'music',
  'john belushi': 'hollywood',
  'psycho': 'hollywood',
  'robin williams': 'hollywood',
  't s eliot': 'literary',
  'emil jannings': 'hollywood',
  'red hot chili peppers': 'music',
  'beverly hillbillies': 'hollywood',
  'harry chapin': 'music',
  'john quincy adams document': 'political',
  'igor sikorsky': 'space-science',
  'franklin pierce document': 'political',
  'ernest shackleton': 'historic',
  'mary astor': 'hollywood',
  'john candy': 'hollywood',
  'chico marx': 'hollywood',
  'pietro mascagni': 'music',
  'charles bukowski': 'literary',
  'marie antoinette': 'royalty',
  'henry wadsworth longfellow signature': 'literary',
  'james buchanan signature': 'political',
  'sonja henie': 'sports',
  'connie mack signature': 'sports',
  'sydney greenstreet': 'hollywood',
  'marlon brando signature': 'hollywood',
  'frederic remington': 'literary',
  'james a garfield free': 'political',
  'j k rowling book': 'literary',
  'millard fillmore book': 'political',
  'sir walter scott': 'literary',
  'prince group': 'music',
  'lon chaney jr': 'hollywood',
  'cal ripken jr': 'sports',
  'horse racing turcotte ron': 'sports',
  'fredric march': 'hollywood',
  'diana dors': 'hollywood',
  'fritz lang': 'hollywood',
  'warren g harding typed': 'political',
  'ward bond': 'hollywood',
  'judy holliday': 'hollywood',
  'rat pack': 'hollywood',
  'robert louis stevenson': 'literary',
  'enzo ferrari': 'historic',
  'lincoln assassination': 'political',
  'king george iii document': 'royalty',
  'doobie brothers': 'music',
  'robert ripley': 'literary',
  'alberto vargas': 'literary',
  'cy young signature': 'sports',
  'john tyler signature': 'political',
  'george m cohan': 'music',
  'jack benny': 'hollywood',
  'george g meade': 'military',
  'skylab': 'space-science',
  'walter brennan': 'hollywood',
  'beatles harrison george': 'music',
  'walter johnson': 'sports',
  'fillmore east': 'music',
  'the band': 'music',
  'gypsy rose lee': 'hollywood',
  'dorothy lamour': 'hollywood',
  'jeff beck': 'music',
  'ronald colman': 'hollywood',
  'jennifer jones': 'hollywood',
  'river phoenix': 'hollywood',
  'pamela anderson': 'hollywood',
  'nicholas ii': 'royalty',
  'uss constitution': 'military',
  'moshe dayan': 'military',
  'abraham lincoln document': 'political',
  'ambrose e burnside': 'military',
  'richard nixon signature': 'political',
  'samuel beckett': 'literary',
  'dire straits': 'music',
  'british prime ministers': 'political',
  'joseph p kennedy': 'political',
  'jay silverheels': 'hollywood',
  'herbert hoover signature': 'political',
  'irene dunne': 'hollywood',
  'count basie': 'music',
  'john c calhoun': 'political',
  'mel ott': 'sports',
  'thomas j stonewall jackson': 'military',
  'olivia newton john': 'music',
  'sidney poitier': 'hollywood',
  'orville wright signature': 'military',
  'bertrand russell': 'literary',
  'edvard grieg': 'music',
  'florence nightingale': 'space-science',
  'rogers hornsby signature': 'sports',
  'franz lehar': 'music',
  'gil hodges': 'sports',
  'dale earnhardt group lot': 'sports',
  'byron nelson': 'sports',
  'linda lovelace': 'hollywood',
  'king kong': 'hollywood',
  'robert de niro': 'hollywood',
  'nancy reagan': 'political',
  'king charles iii': 'royalty',
  'chevy chase': 'hollywood',
  'peter frampton': 'music',
  'robert duvall': 'hollywood',
  'john mccain': 'political',
  'robert f kennedy signature': 'political',
  'ron evans': 'space-science',
  'hermann hesse': 'literary',
  'alex haley': 'literary',
  'william f halsey': 'military',
  'paulette goddard': 'hollywood',
  'payne stewart': 'sports',
  'sam cooke': 'music',
  'william randolph hearst': 'historic',
  'gustave eiffel': 'literary',
  'raymond chandler': 'literary',
  'guglielmo marconi signature': 'space-science',
  'victor herbert': 'music',
  'nigel bruce': 'hollywood',
  'mario lanza': 'music',
  'camille saint saens': 'music',
  'horace greeley': 'political',
  'wilhelm ii': 'royalty',
  'betty hutton': 'hollywood',
  'norman rockwell print': 'literary',
  'john quincy adams free': 'political',
  'harper lee book': 'literary',
  'three presidents': 'political',
  'margot fonteyn': 'literary',
  'cecil b demille': 'hollywood',
  'hugh hefner': 'historic',
  'sherlock holmes': 'hollywood',
  'gilligan s island': 'hollywood',
  'seinfeld': 'hollywood',
  'noel coward': 'literary',
  'eddie cochran': 'music',
  'romy schneider': 'hollywood',
  'carlos santana': 'music',
  'john gotti': 'historic',
  'three stooges signatures': 'hollywood',
  'anthony mcauliffe': 'military',
  'jimmy carter typed letter': 'political',
  'king george iv signature': 'royalty',
  'bill clinton typed letter': 'political',
  'farrah fawcett': 'hollywood',
  'toshiro mifune': 'hollywood',
  'benny goodman': 'music',
  'george w': 'political',
  'james joyce': 'literary',
  'menachem begin': 'political',
  'harpo marx': 'hollywood',
  'vivien leigh typed letter': 'hollywood',
  'charles mingus': 'music',
  'jimmie foxx signature': 'sports',
  'jimmy durante': 'hollywood',
  'jim reeves': 'music',
  'dorothy dandridge': 'hollywood',
  'lord of the rings': 'hollywood',
  'j d salinger': 'literary',
  'james montgomery flagg': 'literary',
  'tris speaker': 'sports',
  'a a milne': 'literary',
  'first ladies group lot': 'political',
  'andy warhol postcard': 'literary',
  'carole landis': 'hollywood',
  'luftwaffe aces': 'military',
  'the monkees': 'music',
  'john travolta': 'hollywood',
  'desi arnaz': 'hollywood',
  'james buchanan document': 'political',
  'pope francis': 'historic',
  'douglas macarthur typed letter': 'military',
  'charles addams': 'literary',
  'lionel barrymore': 'hollywood',
  'tupac shakur': 'music',
  'samuel adams': 'political',
  'john f kennedy signature': 'political',
  'stuart roosa': 'space-science',
  'gideon welles': 'political',
  'abraham lincoln signature': 'political',
  'sergei rachmaninoff signature': 'music',
  'jiminy cricket': 'hollywood',
  'd h lawrence': 'literary',
  'chester gould': 'literary',
  'jean arthur': 'hollywood',
  'pope benedict xvi': 'historic',
  'michael jackson signature': 'music',
  'thelma todd': 'hollywood',
  'philip h sheridan signature': 'military',
  'henry moore': 'literary',
  'juan peron': 'political',
  'josip tito': 'political',
  'carl yastrzemski': 'sports',
  'lovin spoonful': 'music',
  'grandma moses': 'literary',
  'western stars': 'hollywood',
  'mary todd lincoln': 'political',
  'chester a arthur white': 'political',
  'james buchanan free frank': 'political',
  'martin van buren free': 'political',
  'acdc album': 'music',
  'simon and garfunkel': 'music',
  'william butler yeats': 'literary',
  'zz top album': 'music',
  'james taylor guitar': 'music',
  'mitt romney': 'political',
  'pel': 'sports',
  'jimmy page': 'music',
  'marilyn monroe signature': 'hollywood',
  'jon bon jovi': 'music',
  'dolley madison': 'political',
  'joseph stalin': 'political',
  'garth brooks': 'music',
  'cindy crawford': 'hollywood',
  'leonard cohen': 'music',
  'robert plant': 'music',
  'bobby fischer': 'sports',
  'jack johnson': 'sports',
  'camille pissarro': 'literary',
  'woodrow wilson signature': 'political',
  'beatles lennon john': 'music',
  'conrad veidt': 'hollywood',
  'sugar ray leonard': 'sports',
  'norman rockwell typed letter': 'literary',
  'ira gershwin': 'music',
  'john ford': 'hollywood',
  'robert e peary': 'historic',
  'william faulkner': 'literary',
  'honus wagner signature': 'sports',
  'donn eisele': 'space-science',
  'primo carnera': 'sports',
  'max planck': 'space-science',
  'alain delon': 'hollywood',
  'ezzard charles': 'sports',
  'emmett kelly': 'hollywood',
  'george s patton signature': 'military',
  'deborah kerr': 'hollywood',
  'franklin d roosevelt white': 'political',
  'calvin coolidge book': 'political',
  'd w griffith': 'hollywood',
  'jimmy carter group lot': 'political',
  'artists group lot': 'literary',
  'foreigner album': 'music',
  'robert browning': 'literary',
  'lovin spoonful album': 'music',
  'pistol pete maravich': 'sports',
  'alex rodriguez': 'sports',
  'pulp fiction': 'hollywood',
  'anthony hopkins': 'hollywood',
  'vintage hollywood': 'hollywood',
  'woodrow wilson document': 'political',
  'madame chiang kai shek': 'political',
  'jefferson starship': 'music',
  'nikita khrushchev': 'political',
  'mitsuo fuchida': 'military',
  'charlie parker': 'music',
  'jacques cousteau': 'historic',
  'judy garland signature': 'hollywood',
  'everly brothers': 'music',
  'harry s truman white': 'political',
  'tom brady': 'sports',
  'bill clinton signature': 'political',
  'it s a wonderful life': 'hollywood',
  'wwii': 'military',
  'jean paul sartre': 'literary',
  'james longstreet signature': 'military',
  'rosalind russell': 'hollywood',
  'j e b stuart': 'military',
  'fats waller': 'music',
  'leni riefenstahl': 'hollywood',
  'edward elgar': 'music',
  'salmon p chase': 'political',
  'anwar sadat': 'political',
  'robert wagner': 'hollywood',
  'carl jung': 'space-science',
  'ann sheridan': 'hollywood',
  'prince charles': 'royalty',
  'duke snider': 'sports',
  'neil young album': 'music',
  'willie nelson guitar': 'music',
  'nathaniel hawthorne': 'literary',
  'authors group lot': 'literary',
  'x 15': 'space-science',
  'joe dimaggio hall': 'sports',
  'amy winehouse': 'music',
  'maurice chevalier': 'hollywood',
  'sharon stone': 'hollywood',
  'william h taft document': 'political',
  'jacqueline kennedy typed letter': 'political',
  'ethel barrymore': 'hollywood',
  'leonardo dicaprio': 'hollywood',
  'elvis costello': 'music',
  'dan marino': 'sports',
  'the who townshend pete': 'music',
  'peter gabriel': 'music',
  'john brown': 'political',
  'raymond chandler typed letter': 'literary',
  'charles gounod': 'music',
  'aaron copland': 'music',
  'lee van cleef': 'hollywood',
  'charlie s angels': 'hollywood',
  'felix frankfurter': 'political',
  'douglas macarthur signature': 'military',
  'martin van buren signature': 'political',
  'vivien leigh signature': 'hollywood',
  'two guns white calf': 'historic',
  'elijah muhammad': 'historic',
  'grace kelly signature': 'hollywood',
  'grace slick': 'music',
  'john jacob astor': 'historic',
  'arthur miller book': 'literary',
  'millard fillmore free frank': 'political',
  'mother teresa prayer slip': 'historic',
  'truman capote book': 'literary',
  'jimmy and rosalynn carter': 'political',
  'pickguards': 'music',
  'erich hartmann': 'military',
  'cheap trick': 'music',
  'buffalo springfield': 'music',
  'grover cleveland autograph letter': 'political',
  'theodore roosevelt document': 'political',
  'ronald reagan autograph letter': 'political',
  'maria ouspenskaya': 'hollywood',
  'iggy pop': 'music',
  'ed sheeran': 'music',
  'diana ross': 'music',
  'virginia woolf': 'literary',
  'thomas mifflin': 'political',
  'pat garrett': 'historic',
  'white house': 'political',
  'margaret mitchell typed letter': 'literary',
  'bill wilson': 'historic',
  'benjamin harrison document': 'political',
  'stan laurel typed letter': 'hollywood',
  'luise rainer': 'hollywood',
  'everybody loves raymond': 'hollywood',
  'timothy pickering': 'political',
  'addams family': 'hollywood',
  'anthony perkins': 'hollywood',
  'gilda radner': 'hollywood',
  'atomic bomb': 'military',
  'mel ott signature': 'sports',
  'robert morris': 'political',
  'king william iv': 'royalty',
  'william makepeace thackeray': 'literary',
  'jeanette macdonald': 'hollywood',
  'pearl s buck': 'literary',
  'maureen o sullivan': 'hollywood',
  'paul henreid': 'hollywood',
  'abner doubleday': 'military',
  'lefty grove': 'sports',
  'maurice ravel': 'music',
  'charles guiteau': 'historic',
  'merle oberon': 'hollywood',
  'john tyler free frank': 'political',
  'carlton fisk': 'sports',
  'joseph e johnston': 'military',
  'ruggero leoncavallo': 'music',
  'astronauts group lot': 'space-science',
  'yes album': 'music',
  'charles lindbergh book': 'military',
  'gioacchino rossini': 'music',
  'prince set': 'music',
  'gerald and betty ford': 'political',
  'pierre g t beauregard': 'military',
  'gibson incorporated': 'music',
  'jerry lewis': 'hollywood',
  'saturday night live': 'hollywood',
  'erich von stroheim': 'hollywood',
  'bob dylan signature': 'music',
  'gene autry': 'hollywood',
  'st louis': 'other',
  'briar rose': 'hollywood',
  'marie dressler': 'hollywood',
  'back to the future': 'hollywood',
  'anna magnani': 'hollywood',
  'jack lousma': 'space-science',
  'young frankenstein': 'hollywood',
  'kevin costner': 'hollywood',
  'spice girls': 'music',
  'keepsake warriors': 'other',
  'rush': 'music',
  'millard fillmore document': 'political',
  'charlie duke oversized': 'space-science',
  'iron maiden': 'music',
  'james madison document': 'political',
  'dr seuss signature': 'literary',
  'thomas hart benton': 'literary',
  'hogan s heroes': 'hollywood',
  'elizabeth montgomery': 'hollywood',
  'bruce springsteen signature': 'music',
  'harry blackstone': 'hollywood',
  'hap arnold': 'military',
  'susan b anthony signature': 'political',
  'jonathan trumbull': 'political',
  'louis b mayer': 'hollywood',
  'buster keaton signature': 'hollywood',
  'charles cornwallis': 'military',
  'calvin coolidge signature': 'political',
  'john greenleaf whittier': 'literary',
  'charles lindbergh signature': 'military',
  'tris speaker signature': 'sports',
  'thurman munson': 'sports',
  'max schmeling': 'sports',
  'carl laemmle': 'hollywood',
  'ann sothern': 'hollywood',
  'stanley kubrick': 'hollywood',
  'dr seuss book': 'literary',
  'nelson mandela book': 'political',
  'maurice sendak book': 'literary',
  'reggie jackson': 'sports',
  'katharine hepburn typed letter': 'hollywood',
  'roy lichtenstein postcard': 'literary',
  'tarzan': 'hollywood',
  'allman brothers album': 'music',
  'jackson 5': 'music',
  'eddie collins': 'sports',
  'william h taft white': 'political',
  'journey album': 'music',
  'richard boone': 'hollywood',
  'bill robinson': 'hollywood',
  'dr seuss sketch': 'literary',
  'marianne faithfull album': 'music',
  'pittsburgh steelers': 'sports',
  'frank whittle': 'space-science',
  'blondie': 'music',
  'oliver hardy': 'hollywood',
  'the sopranos tony soprano': 'hollywood',
  'jethro tull': 'music',
  'apocalypse now': 'hollywood',
  'russell crowe': 'hollywood',
  'george reeves': 'hollywood',
  'john huston': 'hollywood',
  'calvin coolidge document': 'political',
  'jawaharlal nehru': 'political',
  'ray bolger': 'hollywood',
  'mel brooks': 'hollywood',
  'greer garson': 'hollywood',
  'paul muni': 'hollywood',
  'will rogers signature': 'hollywood',
  'keanu reeves': 'hollywood',
  'julia roberts': 'hollywood',
  'hank ketcham': 'literary',
  'tom waits': 'music',
  'o j simpson': 'sports',
  'pope pius x': 'historic',
  'frances cleveland': 'political',
  'francisco franco': 'political',
  'king philip ii': 'royalty',
  'laurel and hardy signatures': 'hollywood',
  'lionel atwill': 'hollywood',
  'robert e lee signature': 'military',
  'fritz kreisler': 'music',
  'colin clive': 'hollywood',
  'langston hughes': 'literary',
  'rita hayworth signature': 'hollywood',
  'grace coolidge': 'political',
  'righteous brothers': 'music',
  'william fargo': 'historic',
  'ingrid bergman signature': 'hollywood',
  'p t barnum signature': 'historic',
  'booker t washington signature': 'political',
  'roy o disney': 'hollywood',
  'robert baden powell': 'military',
  'isaac asimov': 'literary',
  'golden girls': 'hollywood',
  'nellie fox': 'sports',
  'gene sarazen': 'sports',
  'auto racing': 'sports',
  'thelonious monk': 'music',
  'maxim gorky': 'literary',
  'phil rizzuto': 'sports',
  'john burroughs': 'literary',
  'howard carter': 'historic',
  'cecil b': 'hollywood',
  'mercury': 'space-science',
  'kiss album': 'music',
  'peter lawford signature': 'hollywood',
  'branch rickey': 'sports',
  'william h taft book': 'political',
  'odd couple': 'hollywood',
  'james madison and james monroe': 'political',
  'diana and charles': 'royalty',
  'metallica': 'music',
  'yousuf karsh': 'literary',
  'otis redding': 'music',
  'godfather': 'hollywood',
  'woody allen': 'hollywood',
  'charles boyer': 'hollywood',
  'ida lupino': 'hollywood',
  'diana rigg': 'hollywood',
  'zachary taylor signature': 'political',
  'thomas mitchell': 'hollywood',
  'henry hill': 'historic',
  'jacob ruppert': 'sports',
  'francis ford coppola': 'hollywood',
  'paul simon': 'music',
  'charles bronson': 'hollywood',
  'george washington signature': 'political',
  'franklin d roosevelt document': 'political',
  'giuseppe garibaldi': 'political',
  'beatrix potter': 'literary',
  'all in the family': 'hollywood',
  'ernest borgnine': 'hollywood',
  'al worden s': 'space-science',
  'rudyard kipling signature': 'literary',
  'world war ii aces': 'military',
  'bill tilden': 'sports',
  'james madison signature': 'political',
  'warren beatty': 'hollywood',
  'karl lagerfeld': 'literary',
  'gettysburg': 'military',
  'wiley post': 'military',
  'nick adams': 'hollywood',
  'alexander stephens': 'political',
  'james mason': 'hollywood',
  'natalie wood signature': 'hollywood',
  'fanny brice': 'hollywood',
  'lenny bruce': 'hollywood',
  'akira kurosawa': 'hollywood',
  'john marshall': 'political',
  'robert mccall': 'literary',
  'elliot see': 'space-science',
  'warner oland': 'hollywood',
  'dee dee ramone': 'music',
  'rocky marciano signature': 'sports',
  'woody guthrie': 'music',
  'george clinton': 'political',
  'king louis xiv': 'royalty',
  'king george iv': 'royalty',
  'lupe velez': 'hollywood',
  'pittsburgh pirates': 'sports',
  'sammy baugh': 'sports',
  'king george ii': 'royalty',
  'herbert hoover white house': 'political',
  'cartoonists group lot': 'literary',
  'presidents and first ladies': 'political',
  'billy joel album': 'music',
  'charles schulz print': 'literary',
  'alfred hitchcock sketch': 'hollywood',
  'theodore roosevelt book': 'political',
  'lynyrd skynyrd album': 'music',
  'richard nixon engraving': 'political',
  'henry james': 'literary',
  'pink floyd album': 'music',
  'pie traynor': 'sports',
};
