/**
 * gen-redirects.ts — build-generates public/_redirects for Cloudflare Pages.
 * Runs before `next build` (see package.json build script).
 *
 * ORDER MATTERS on CF Pages: rules are evaluated top-down, first match wins,
 * and redirects SHADOW static assets — so every flagged lot's static page is
 * pinned with a self-proxy 200 ABOVE the /lot/* catch-all rewrite, or the
 * shell would swallow the prerendered pages (audit-urls §4A).
 *
 * Budget: 2,000 static + 100 dynamic rules; we emit ~60 static + 1 dynamic.
 */
import fs from 'fs';
import path from 'path';
import { ARTISTS } from '../app/constants';
import { flaggedLots } from '../app/lot/flagged';

const lines: string[] = [
  '# GENERATED by scripts/gen-redirects.ts — do not edit by hand.',
  '',
  '# legacy → canonical (301s keep every inbound link + OG card alive)',
  '/preview/terminal   /          301',
  '/collectibles       /          301',
  '/artists            /makers    301',
  '/saved              /profile   301',
  '',
  '# root maker slugs moved under /makers (generated from ARTISTS)',
];

for (const a of ARTISTS) {
  lines.push(`/${a.slug}   /makers/${a.slug}   301`);
}

lines.push(
  '',
  '# universal lot permalinks: pin each flagged STATIC page to itself (200',
  '# self-proxy serves the asset), THEN rewrite everything else to the shell',
);
for (const l of flaggedLots()) {
  const id = encodeURIComponent(l.id);
  lines.push(`/lot/${id}   /lot/${id}   200`);
}
lines.push('/lot/*   /lot   200', '');

const out = lines.join('\n');
fs.writeFileSync(path.join(process.cwd(), 'public', '_redirects'), out);
const staticRules = lines.filter(l => l && !l.startsWith('#')).length - 1;
console.log(`[redirects] wrote public/_redirects: ${staticRules} static rules + 1 dynamic catch-all`);
